# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- '*'

variables:
  uiSource: 'client'
  uiBuild: '$(uiSource)/build'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.14'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run install-client
    npm run install-server
    pushd $(uiSource)
    npm run build
    popd
  displayName: 'npm install and build'

- task: Npm@1
  displayName: Running unit tests
  inputs:
    command: 'custom'
    workingDir: 'client/'
    customCommand: 'run test:ci'

- task: PublishTestResults@2
  displayName: Sending Test Results to Pipeline
  inputs:
    testResultsFiles: 'client/junit.xml'
  condition: succeededOrFailed()

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       npm run build
# - task: Npm@1
#   inputs:
#     command: 'custom'
#     customCommand: 'run build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pwd
      ls client/build
      

# - script: 
#     set "REACT_APP_STAGE=$(stage)" && npm run build
#   displayName: 'npm build'
#   workingDirectory: '/'
 
- task: PublishTestResults@2
  displayName: 'supply npm test results to pipelines'
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'client/junit.xml'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(uiBuild)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'